"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {ActivityChart} from "@/components/admin/ActivityChart";
import {AccessToken} from "@/lib/types";
type Stats={total:number;pages:{page:string;count:number}[];days:{date:string;count:number}[]};
export default function AdminTokens(){
 const supabase=useMemo(()=>createClient(),[]);
 const [tokens,setTokens]=useState<AccessToken[]>([]),[selected,setSelected]=useState(""),[stats,setStats]=useState<Stats|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[copied,setCopied]=useState("");
 const load=useCallback(async()=>{const {data,error}=await supabase.from("access_tokens").select("*").order("created_at",{ascending:false});if(error)setError("No s’han pogut carregar els accessos.");else{setTokens(data||[]);setSelected(old=>(data||[]).some(t=>t.id===old)?old:(data?.[0]?.id||""));}setLoading(false);},[supabase]);
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("access-links-changed",refresh);return()=>window.removeEventListener("access-links-changed",refresh);},[load]);
 useEffect(()=>{let live=true;setStats(null);if(selected)void supabase.rpc("about_access_stats",{link_id:selected}).then(({data,error})=>{if(!live)return;if(error)setError("No s’han pogut carregar les visites.");else setStats(data as Stats);});return()=>{live=false;};},[selected,supabase,tokens]);
 async function create(){const label=prompt("Nom de la persona o empresa");if(!label?.trim())return;setBusy(true);const {error}=await supabase.from("access_tokens").insert({label:label.trim().slice(0,120),token:crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-",""),active:true,expires_at:new Date(Date.now()+60*86400000).toISOString()});setBusy(false);if(error)setError("No s’ha pogut crear l’accés.");else await load();}
 async function toggle(t:AccessToken){setBusy(true);const {error}=await supabase.from("access_tokens").update({active:!t.active}).eq("id",t.id);setBusy(false);if(error)setError("No s’ha pogut canviar l’estat.");else await load();}
 async function remove(t:AccessToken){if(!confirm(`Vols eliminar l’accés de ${t.label}? L’enllaç deixarà de funcionar.`))return;setBusy(true);const {error}=await supabase.from("access_tokens").delete().eq("id",t.id);setBusy(false);if(error)setError("No s’ha pogut eliminar l’accés.");else{await load();location.reload();}}
 const chart=Array.from({length:30},(_,i)=>{const d=new Date();d.setDate(d.getDate()-29+i);const iso=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Madrid",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);return{date:d.toLocaleDateString("ca-ES",{day:"numeric",month:"short"}),count:stats?.days.find(x=>x.date===iso)?.count||0};});
 return <section id="accessos" className="space-y-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-2xl">Accessos de Sobre mi</h2><p className="text-sm text-[var(--color-muted)] mt-2">Consulta, copia, desactiva o elimina els enllaços personals.</p></div><button disabled={busy} className="access-primary" onClick={create}>Nou enllaç</button></div>{error&&<p role="alert">{error}</p>}{loading?<p>Carregant accessos…</p>:!tokens.length?<p>No hi ha accessos.</p>:<>
 <div className="grid sm:grid-cols-2 gap-3">{tokens.map(t=>{const expired=!!t.expires_at&&new Date(t.expires_at)<new Date();return <article key={t.id} className="rounded-xl border border-[var(--color-border)] p-5"><h3 className="font-semibold">{t.label}</h3><p className="text-xs text-[var(--color-muted)] mt-2">{!t.active?"Desactivat":expired?"Caducat":"Actiu"} · Caduca: {t.expires_at?new Date(t.expires_at).toLocaleDateString("ca-ES"):"Mai"}</p><div className="flex flex-wrap gap-2 mt-4"><button className="access-secondary" onClick={()=>setSelected(t.id)} aria-pressed={selected===t.id}>Veure visites</button><button className="access-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/v/${t.token}/sobre-mi`);setCopied(t.id);}catch{setError("No s’ha pogut copiar l’enllaç.");}}}>{copied===t.id?"Copiat":"Copiar"}</button><button disabled={busy} className="access-secondary" onClick={()=>toggle(t)}>{t.active?"Desactivar":"Activar"}</button><button disabled={busy} className="access-secondary" onClick={()=>remove(t)}>Eliminar</button></div></article>;})}</div>
 <div className="border border-[var(--color-border)] rounded-xl p-6"><label className="block text-sm mb-5">Estadístiques de l’accés<select className="block mt-2 w-full bg-[var(--color-surface)] border border-[var(--color-border)] rounded-lg p-3" value={selected} onChange={e=>setSelected(e.target.value)}>{tokens.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>{stats?<><p className="text-3xl mb-2">{stats.total} <span className="text-base text-[var(--color-muted)]">pàgines vistes amb aquest enllaç</span></p><p className="text-sm text-[var(--color-muted)] mb-5">Activitat dels últims 30 dies. Cada pàgina oberta compta com una visita; no són persones úniques. Les visites de l’administrador no es compten.</p><ActivityChart data={chart}/><h3 className="mt-8 mb-4 text-lg">Visites per pàgina · Tot el període</h3>{stats.pages.length?stats.pages.map(p=><div key={p.page} className="mb-4"><div className="flex justify-between gap-3 text-sm"><span className="break-all">{p.page}</span><span>{p.count}</span></div><div className="h-2 rounded-full bg-[var(--color-border)] mt-2"><div className="h-full rounded-full bg-[var(--color-text)]" style={{width:`${Math.max(1,p.count/Math.max(...stats.pages.map(p=>p.count))*100)}%`}}/></div></div>):<p className="text-sm text-[var(--color-muted)]">Aquest accés encara no té visites registrades.</p>}</>:<p>Carregant estadístiques…</p>}</div>
 </>}</section>;
}
