"use client";
import {useState} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowUpRight,Sun,Moon} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {useRouter} from "next/navigation";
import {LanguageFlag} from "@/components/ui/LanguageFlag";
export default function AdminLogin(){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[dark,setDark]=useState(false);
 const router=useRouter();
 async function login(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");const {error}=await createClient().auth.signInWithPassword({email,password});if(error){setError("El correu o la contrasenya no són correctes. Torna-ho a provar.");setLoading(false);return;}const state=new URLSearchParams(location.search).get("calendar_state");if(state&&/^[a-f0-9]{64}$/.test(state)){location.assign(`/api/calendar/access?state=${state}`);return;}router.push("/admin/dashboard");router.refresh();}
 return <div className="descobreix-access"><div className="absolute top-6 right-6 flex gap-3 items-center"><span className="flex gap-2 items-center text-sm"><LanguageFlag code="ca"/>Català</span><button type="button" aria-label="Canviar aparença" onClick={()=>{const value=document.documentElement.dataset.studioTheme!=="dark";document.documentElement.dataset.studioTheme=value?"dark":"light";localStorage.setItem("studio-theme",value?"dark":"light");setDark(value);}} className="access-secondary">{dark?<Sun size={17}/>:<Moon size={17}/>}</button></div><section className="descobreix-access-intro"><Link href="/" className="flex gap-2 items-center text-sm"><ArrowLeft size={17}/>Tornar al web</Link><div><p className="text-sm uppercase tracking-widest text-[var(--color-muted)] mb-5">Descobreix</p><h1 className="text-5xl sm:text-6xl leading-tight">El teu espai.<br/>Tot connectat.</h1><p className="text-[var(--color-muted)] mt-6 max-w-sm">Gestiona els projectes, el blog i el teu perfil. Accedeix al calendari Move amb el mateix compte.</p></div><p className="text-xs text-[var(--color-muted)] mt-6">Disseny · Comunitat · Trajectòria</p></section><section className="descobreix-access-card"><p className="text-xs uppercase tracking-widest text-[var(--color-muted)]">Administració</p><h2 className="text-3xl mt-3">Benvingut de nou</h2><p className="text-sm text-[var(--color-muted)] mt-3 mb-8">Inicia sessió per editar Descobreix.</p><form onSubmit={login} className="space-y-5"><label className="block text-sm" htmlFor="admin-email">Correu electrònic<input id="admin-email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm" htmlFor="admin-password">Contrasenya<input id="admin-password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="text-sm">{error}</p>}<button disabled={loading} className="access-primary w-full">{loading?"Verificant…":"Iniciar sessió"}<ArrowUpRight size={17}/></button></form></section></div>;
}
